services:
  - type: web
    name: iris-keras-classifier
    runtime: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python app.py
